// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nigqzcxuyzowjhywsvon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZ3F6Y3h1eXpvd2poeXdzdm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjQ1NTcsImV4cCI6MjA2MDQ0MDU1N30.TeCqcWCBoSRE5bm48ptgIKAF_QuUtx3CIKz9PWcBYgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);